### PR TITLE
Add Mybatis plugin

### PR DESCRIPTION
**Pull request by alex8224**
1. Add Mybatis plugin
2. add byte[] key to jedis Interceptor.

### CODE REVIEW

**Comment by wu-sheng** [comment]
@alex8224 SkyWalking project is moving to Apache Incubator project. The process is on going, so, the merge is suspend.

Thanks for you understanding. Hope you can resend the pull request after we move to apache/skywalking. Make sense?

**Comment by wu-sheng** [comment]
# Announcement:

## SkyWalking has been accepted as an incubator project by Apache Foundation. All pull requests can't be accepted until Apache/SkyWalking repository established.

**Comment by wu-sheng** [comment]
@alex8224 And I have too questions about your pull request, even we are not going to merge at this moment.

1. Your avatar(image) is not right, which means your github account primary mail is not same as your local git mail. Which will cause your contributions can't be filed(documented in GitHub). That is definitely a blocking.
1. Why need a Mybatis? What are the advantages than normal jdbc plugins?

**Comment by alex8224** [comment]
@wu-sheng Because postgresql plugin not working in my env. same as #580 . so, True jdbc is better that mybatis

**Pull request closed without merging**
