### PR TITLE
AgentStream NullPointerException with RemoteWorker

### PR DESCRIPTION
**Pull request by zhangkewei**
3.2.3中增加了SegmentStandardizationWorker用于校验Segment，缺失信息的样本会被丢弃，所以一些默认值判断、赋值就给去掉了。但是在多于一个collector的集群中会存在均衡负载的逻辑，在RemoteMessage通过GRPC序列化传输的时候，默认值为NULL的字段导致报错。

### CODE REVIEW

**Comment by zhangkewei** [comment]
npm

**Comment by wu-sheng** [comment]
@zhangkewei I think this is a quick fix for 3.2.3, right? We are working on 3.2.4 with new modulization and graph-stream mechanism in `feature/collector-modelization` branch. 

@peng-yongsheng Do we need to release 3.2.3.1 to fix this?

**Comment by wu-sheng** [comment]
We already found by dangdang's reporting, see #551. But I am not sure the strategy to deal with it.

**Comment by zhangkewei** [comment]
@wu-sheng 查看了@chidaodezhongsheng的贴图，确实是同一个问题。在我们公司环境已经做了修复并验证。

**Pull request merged**
